### ISSUE TITLE
ghcr.io/go-shiori/shiori:latest wrong version -- web extionsion error 404

### ISSUE THREAD

**Issue by rmayergfx** [go-shiori/shiori#733]
Something is going wrong here...

ghcr.io/go-shiori/shiori:latest is not loading v1.5.5, instead some pre 1.6, killed today my instance on synology nas.

ghcr.io/go-shiori/shiori:latest
sha256:2451d9754f329ffeb494cdc465bd86d934efaea996e46ac6595c6421e3a47e7d
v1.6xxx
time="2023-09-15T12:42:25Z" level=info msg="Starting Shiori v1.6.0-next"

v1.5.5
sha256:6dc5c6256cc6b1f87a7f404f4206463e4190d10c9ce302fab30eed343b3f1287

Got system back with backup of the docker folder and 
docker pull ghcr.io/go-shiori/shiori:v1.5.5

After Update to latest (1.6.x) the system throws an error 404. To fix this, is started with a new clean database, but this is not working with web extension 0.8.7, no login, always error 404 with Firefox and Chrome, both latest release. Back on v.1.5.5 all works fine again.

**Comment by fmartingr** [comment]
Hey @rmayergfx thanks for the report. This should have not happened. I have reverted `latest` to v1.5.5 and I'm going to check which version got pushed to `latest` and when.

Regarding the upgrade breaking for you, you mean that any URL gave 404 for you?

**Comment by fmartingr** [comment]
Bogus run that pushed to `latest`: https://github.com/go-shiori/shiori/actions/runs/6149062211/job/16684470054.

There was a typo in the bash script [here](https://github.com/go-shiori/shiori/actions/runs/6149062211/job/16684470054#step:5:15) that got fixed [here](https://github.com/go-shiori/shiori/commit/1d52569731e72d2dcb4236f3008912b58a310f6d), but we didn't notice it until now.

**Comment by rmayergfx** [comment]
> Hey @rmayergfx thanks for the report. This should have not happened. I have reverted `latest` to v1.5.5 and I'm going to check which version got pushed to `latest` and when.
> 
> Regarding the upgrade breaking for you, you mean that any URL gave 404 for you?

Yes, system was no longer working. Getting error on Webpage and also with a clean database it is not possible to use 1.6 with web extension 0.8.7, login to get the cookie is reporting error 404.

**Comment by fmartingr** [comment]
That's super weird. I have been updating my personal instance along to latest rcs and it works perfectly. I will try to do a 1.5.5 to 1.6.0-rc to check what's going on.

**Comment by fmartingr** [comment]
I just tried an upgrade locally from 1.5.5 to latest `master` and it worked, webserver was accesible and bookmarks were there. Can you give me more information about your setup? (environment variables to setup shiori, if you set the command to run manually, etc). Obviously removing any sensitive/irrelevant information.

**Comment by rmayergfx** [comment]
it´s very easy to explain.

i have a scheduled task once a week that is grabbing the latest image:
docker pull ghcr.io/go-shiori/shiori:latest

along with other images. The system tells me after the script is finished, which images are updated. I back the data and settings then i stop and reset the matching container,

there is no automation like in watchtower, so i can see if an when an image is updatet.

So i was able to see in portainer that the sha for both images are different and the protokoll shows me after the update was done that the protokoll is showing info msg="Starting Shiori v1.6.0-next"

and that was strange, as here in git v1.5.5 is shown as latest.

**Comment by fmartingr** [comment]
I meant what configuration your shiori deployment have, like environment variables, commands ,etc. Or if you are using the defaults, to test what could have gone wrong.

**Comment by rmayergfx** [comment]
Sorry, here is my install script, run with a scheduler as root:

> docker run -e "SHIORI_DIR=/srv/shiori" -d --name=shiori_go_shiori \
-p 41955:8080 \
-v /volume1/docker/shiori_go_shiori:/srv/shiori \
--restart always \
ghcr.io/go-shiori/shiori:latest

**Comment by beanpuppy** [comment]
@fmartingr I had this problem too and had to revert back to `v1.5.5`. It seems like `latest` only has the `linux/arm64` platform. Running `docker pull --platform=linux/amd64 ghcr.io/go-shiori/shiori:latest` will download with this message:
> image with reference ghcr.io/go-shiori/shiori:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64

`docker inspect ghcr.io/go-shiori/shiori:latest` also confirms that the arm version is being used.

**Comment by janaxhell** [comment]
I am having the same problem on docker x86, but I cannot revert to v1.5.5, what tag do you use? I keep getting 
`Request failed with status code 404` when I try to deploy `ghcr.io/go-shiori/shiori:v1.5.5`

**Comment by rmayergfx** [comment]
This one was working for me: 
docker pull ghcr.io/go-shiori/shiori:v1.5.5
taken from https://github.com/go-shiori/shiori/pkgs/container/shiori/112677461?tag=v1.5.5
and as we can see, the tag latest points out to a different version:
https://github.com/go-shiori/shiori/pkgs/container/shiori/128376074?tag=latest
sha checksum differs from v1.5.5
sha256:296c603c55a803bc0ca02d9d2f2feb43b84352069b380b61df45f8cd0a6c7bb3 
latest:
sha256:67f5369d2379b7a61ffda445acf3c90fe2c07212ba008b71497db2faa91a7d56

**Comment by JourneyOver** [comment]
yep getting the same error message as @janaxhell with the:
```
exec /usr/bin/shiori: exec format error
exec /usr/bin/shiori: exec format error
exec /usr/bin/shiori: exec format error
exec /usr/bin/shiori: exec format error
```

being constantly thrown on 1.5.5

**Comment by fmartingr** [comment]
Please, use v1.5.5 for now until I can fix the latest image. 

Sent from my phone

**Comment by rmayergfx** [comment]
Can you please set latest to the working v1.5.5 until it is fixed?

**Comment by fmartingr** [comment]
I had to jump in a codespace to fix the tag because I'm currently away, can someone confirm that the `latest` tag is fixed? Should be recreated from the 1.5.5 code and to all supported platforms.

**Comment by beanpuppy** [comment]
`latest` is working for me.

**Comment by janaxhell** [comment]
Not so fast, :latest is not working for me, I'm still getting 
`exec /usr/bin/shiori: exec format error`

To make it work I MUST use `:v1.5.5`, in which case I get
`time="2023-09-20T16:45:10Z" level=info msg="Serve shiori in :8080 /"`
and Shiori works fine.

FYI my docker-compose (x86 machine)

```
version: "3"
services:
  shiori:
    image: ghcr.io/go-shiori/shiori:latest
    container_name: shiori
    environment:
      - PUID=998
      - PGID=100
      - SHIORI_DIR=/data
    ports:
      - 5852:8080
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Shiori:/data

networks:
  default:
    external:
      name: omv1

```

**Comment by fmartingr** [comment]
Have you deleted your local image and pulled again? Both latest and v1.5.5 were recreated at the same time. 

Sent from my phone

**Comment by janaxhell** [comment]
Ahh, sorry, yes, after (force) removing all shiori images, I could deploy using `:latest `
It works fine now, thanks

**Comment by fmartingr** [comment]
> Ahh, sorry, yes, after (force) removing all shiori images, I could deploy using `:latest `
> 
> It works fine now, thanks

Awesome to hear that :)

**Comment by rmayergfx** [comment]
Hello, just tried to use the fixed version. Deleted all old images and containters and did a fresh clean install with tag :latest

now i get inside the docker error:

> Failed to open database: unable to open database file: out of memory (14)

There is a new clean folder created and shiori should install a fresh clean database, but nothing happens.

**Comment by fmartingr** [comment]
I'm unsure whats going on on your system, but that totally seems like a permissions issue from your docker to the data volume. Does it work using it without mounting the folders to any volumes for you? I just tried it locally and it runs, so I'm inclined to think is a premissions issue over the volume/folder you have mounted the shiori data into.

Regarding the other docker image I don't know where it's built from, but it seems pretty similar to ours (except that it creates a shiori folder for the data).
